# Generated by Django 2.1.7 on 2019-03-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Donnez un nom pour l'étudiant", max_length=50)),
                ('prenom', models.CharField(help_text="Donnez un prenom pour l'étudiant", max_length=50)),
                ('date_de_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('Homme', 'M'), ('Femme', 'F')], help_text="Choisissez un sexe pour l'étudiant", max_length=1)),
                ('Matricule', models.CharField(help_text="Le matricule de l'étudiant", max_length=50)),
                ('option', models.CharField(choices=[('IG2', 'M'), ('IG3', 'F'), ('IG3', 'F'), ('IG3', 'F'), ('IG3', 'F'), ('IG3', 'F')], default='IG2', max_length=4)),
                ('adresse', models.CharField(max_length=100)),
                ('photo', models.FileField(help_text="Photo de l'étudiant", upload_to='identiter')),
                ('description', models.TextField()),
            ],
        ),
    ]
