# Generated by Django 2.1.7 on 2019-03-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='option',
            field=models.CharField(choices=[('IG2', 'IG2'), ('IG3', 'IG3'), ('MI1', 'MI2'), ('TL1', 'TL1')], default='IG2', max_length=4),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(help_text="Photo de l'étudiant", upload_to='identiter'),
        ),
    ]
