# Generated by Django 2.1.7 on 2019-03-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0002_auto_20190330_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.FileField(help_text="Photo de l'étudiant", upload_to='identiter'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'M'), ('Femme', 'F')], help_text="Choisissez un sexe pour l'étudiant", max_length=5),
        ),
    ]
