# Generated by Django 2.1.7 on 2019-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0003_auto_20190330_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Language', models.CharField(choices=[('Python', 'Python'), ('Ruby', 'Ruby'), ('C++', 'C++'), ('C', 'C'), ('Java', 'Java'), ('javaScript', 'javaScript'), ('Php', 'Php')], help_text="Choisissez un Language pour l'étudiant", max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Langue', models.CharField(choices=[('Français', 'Français'), ('Anglais', 'Anglais'), ('Chinois', 'Chinois'), ('Russe', 'Russe'), ('Arabe', 'Arabe'), ('', ''), ('', '')], help_text="Choisissez une Langue pour l'étudiant", max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='description',
            new_name='Description',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='option',
            field=models.CharField(choices=[('IG1', 'IG1'), ('IG2', 'IG2'), ('IG3', 'IG3'), ('MI1', 'MI1'), ('MI2', 'MI2'), ('MI3', 'MI3'), ('TL1', 'TL1'), ('TL2', 'TL2'), ('TL3', 'TL3')], default='IG2', max_length=4),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], help_text="Choisissez un sexe pour l'étudiant", max_length=5),
        ),
    ]
